version: '3'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
  react-app:
    build: ./react-front
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:5000/upload
  redis:
    image: redis
networks:
  red: